# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # schema: classpath:db/schema-mysql.sql
    # data: classpath:db/data-mysql.sql
    url: jdbc:mysql://127.0.0.1:3306/dingtou?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai&useSSL=false
    username: dingtou
    password: DingTou.Me



  # FREEMARKER (FreeMarkerAutoConfiguration)
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/ #comma-separated list

  resources:
    static-locations: classpath:/static/


  jackson:
    generator:
      write_numbers_as_strings: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

